CREATE TABLE CANALES
	(AREA INT IDENTITY (1,1) PRIMARY KEY NOT NULL,
	NOMBRE_DEL_CANAL VARCHAR(25) NOT NULL,
	ID VARCHAR(MAX) NOT NULL)


CREATE TABLE ALERTS
	(AlertID INT IDENTITY (1,1) PRIMARY KEY NOT NULL,
	AlertName VARCHAR(25) NOT NULL,
	AlertDescription VARCHAR(25) NOT NULL,
	AlertActivo BIT NOT NULL,
	Area INT NOT NULL,
	AlertDate DATE NOT NULL)


